### ISSUE TITLE
Undefined property `original_application_version`

### ISSUE THREAD

**Issue by xjewer** [alxmsl/AppStoreClient#4]
Sometimes App Store Receipt in iOS 7 can't consist `original_application_version` field and happen parse error in https://github.com/alxmsl/AppStoreClient/blob/master/source/Response/iOS7/AppReceipt.php#L112
 
http://stackoverflow.com/questions/20629205/cant-get-the-original-application-version-from-the-app-store-receipt-in-ios-7

**Comment by alxmsl** [comment]
It was fixed in #5
